version: "3.8"
services:
  backend:
    container_name: spring-boot
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./backend:/backend"